### ISSUE TITLE
Better Random numbers

### ISSUE THREAD

**Issue by vbjay** [ZdsAlpha/BitTorrentTracker#1]
See [RNGCryptoServiceProvider.GetNonZeroBytes](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rngcryptoserviceprovider.getnonzerobytes(v=vs.110).aspx)

**Comment by ZdsAlpha** [comment]
In this case all bytes in byte array will be non-zero. While transaction_id can or cannot be zero. It can even be fixed but problem occurs when another client with same transaction_id connects to server.

**Comment by ZdsAlpha** [comment]
A huge update is released. Check it out. (Random is fixed)

**Comment by vbjay** [comment]
http://sleeplessmonkey.blogspot.com/2009/03/difference-in-random-number-generation.html

**Comment by ZdsAlpha** [comment]
Implemented RNGCryptoServiceProvider.
